### ISSUE TITLE
[DEV SITE] Elasticsearch server keeps failing

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/hardwoods_site#108]
We'll need to reinstall ES on the Dev server and reconfigure it because I can't figure out why it keeps shutting down on its own.

**Comment by almasaeed2010** [comment]
Error stack that may have caused ES to stop:
```
[2018-01-25T08:09:50,344][WARN ][o.e.b.JNANatives         ] unable to install syscall filter: 
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
	at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:342) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:617) ~[elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:258) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:111) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:195) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.5.jar:5.6.5]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.5.jar:5.6.5]
[2018-01-25T08:09:50,586][INFO ][o.e.n.Node               ] [elasticsearch_HGD] initializing ...
[2018-01-25T08:09:50,941][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch_HGD] using [1] data paths, mounts [[/data (/dev/md126p3)]], net usable_space [252.8gb], net total_space [825.5gb], spins? [possibly], types [ext4]
[2018-01-25T08:09:50,942][INFO ][o.e.e.NodeEnvironment    ] [elasticsearch_HGD] heap size [7.9gb], compressed ordinary object pointers [true]
[2018-01-25T08:09:50,997][INFO ][o.e.n.Node               ] [elasticsearch_HGD] node name [elasticsearch_HGD], node ID [KaJklRYMQnSHgJ2k4FmCVw]
[2018-01-25T08:09:50,997][INFO ][o.e.n.Node               ] [elasticsearch_HGD] version[5.6.5], pid[29794], build[6a37571/2017-12-04T07:50:10.466Z], OS[Linux/2.6.32-696.18.7.el6.x86_64/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_151/25.151-b12]
[2018-01-25T08:09:50,997][INFO ][o.e.n.Node               ] [elasticsearch_HGD] JVM arguments [-Xms8g, -Xmx8g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/usr/share/elasticsearch]
[2018-01-25T08:09:52,237][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [aggs-matrix-stats]
[2018-01-25T08:09:52,237][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [ingest-common]
[2018-01-25T08:09:52,237][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [lang-expression]
[2018-01-25T08:09:52,237][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [lang-groovy]
[2018-01-25T08:09:52,237][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [lang-mustache]
[2018-01-25T08:09:52,237][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [lang-painless]
[2018-01-25T08:09:52,237][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [parent-join]
[2018-01-25T08:09:52,238][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [percolator]
[2018-01-25T08:09:52,238][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [reindex]
[2018-01-25T08:09:52,238][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [transport-netty3]
[2018-01-25T08:09:52,238][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] loaded module [transport-netty4]
[2018-01-25T08:09:52,238][INFO ][o.e.p.PluginsService     ] [elasticsearch_HGD] no plugins loaded
[2018-01-25T08:09:54,110][INFO ][o.e.d.DiscoveryModule    ] [elasticsearch_HGD] using discovery type [zen]
[2018-01-25T08:09:54,688][INFO ][o.e.n.Node               ] [elasticsearch_HGD] initialized
[2018-01-25T08:09:54,688][INFO ][o.e.n.Node               ] [elasticsearch_HGD] starting ...
[2018-01-25T08:09:54,890][INFO ][o.e.t.TransportService   ] [elasticsearch_HGD] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2018-01-25T08:09:54,903][WARN ][o.e.b.BootstrapChecks    ] [elasticsearch_HGD] max number of threads [1024] for user [elasticsearch] is too low, increase to at least [2048]
[2018-01-25T08:09:54,903][WARN ][o.e.b.BootstrapChecks    ] [elasticsearch_HGD] system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
[2018-01-25T08:09:57,944][INFO ][o.e.c.s.ClusterService   ] [elasticsearch_HGD] new_master {elasticsearch_HGD}{KaJklRYMQnSHgJ2k4FmCVw}{svSaouVSRGGEgdBkmB3i_Q}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2018-01-25T08:09:57,978][INFO ][o.e.h.n.Netty4HttpServerTransport] [elasticsearch_HGD] publish_address {127.0.0.1:9203}, bound_addresses {[::1]:9203}, {127.0.0.1:9203}
[2018-01-25T08:09:57,978][INFO ][o.e.n.Node               ] [elasticsearch_HGD] started
[2018-01-25T08:09:58,887][INFO ][o.e.g.GatewayService     ] [elasticsearch_HGD] recovered [3] indices into cluster_state
[2018-01-25T08:10:06,565][INFO ][o.e.c.r.a.AllocationService] [elasticsearch_HGD] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[entities][2], [entities][3]] ...]).
```

**Comment by almasaeed2010** [comment]
This issue could be hot-fixed using supervisord

note: see #113
